DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS users;
DROP SEQUENCE IF EXISTS global_seq;

CREATE SEQUENCE GLOBAL_SEQ
  AS INTEGER
  START WITH 100000;

CREATE TABLE users
(
  id       INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name     VARCHAR(255)          NOT NULL,
  email    VARCHAR(255)          NOT NULL,
  enabled  BOOLEAN DEFAULT FALSE NOT NULL,
  password VARCHAR(255)          NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx
  ON USERS (email);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES USERS (id)
    ON DELETE CASCADE
);

CREATE TABLE restaurants
(
  id      INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  user_id INTEGER      NOT NULL,
  name    VARCHAR(255) NOT NULL,
  dish    varchar(255),
  price   INT,
  vote    INT,
  FOREIGN KEY (user_id) REFERENCES USERS (id)
    ON DELETE CASCADE
);
CREATE UNIQUE INDEX restaurants_unique_user
  ON restaurants (user_id, name);